# Generated by Django 4.2.11 on 2024-04-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_m', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Price (Medium)')),
                ('price_l', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Price (Large)')),
                ('imageb', models.ImageField(blank=True, null=True, upload_to='burger_images/', verbose_name='Burger Image')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, choices=[('M', 'Medium'), ('L', 'Large')], max_length=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.TextField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_m', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Price (Medium)')),
                ('price_l', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Price (Large)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pizza_images/', verbose_name='Pizza Image')),
            ],
        ),
    ]
