# Generated by Django 5.0.3 on 2024-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_burger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='imageb',
            field=models.ImageField(blank=True, null=True, upload_to='pizza_images/', verbose_name='Burger Image'),
        ),
    ]
