# Generated by Django 4.2.11 on 2024-04-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_burger_imageb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='imageb',
            field=models.ImageField(blank=True, null=True, upload_to='burger_images/', verbose_name='Burger Image'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('burgers', models.ManyToManyField(blank=True, related_name='orders', to='food.burger')),
                ('pizzas', models.ManyToManyField(blank=True, related_name='orders', to='food.pizza')),
            ],
        ),
    ]
