# Generated by Django 4.2.11 on 2024-04-05 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
    ]
