# Generated by Django 4.2.11 on 2024-04-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_burger_imageb'),
        ('food', '0005_order_note'),
    ]

    operations = [
    ]
