# Generated by Django 4.2.11 on 2024-04-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_merge_0003_alter_burger_imageb_0005_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='imageb',
            field=models.ImageField(blank=True, null=True, upload_to='burger_images/', verbose_name='Burger Image'),
        ),
    ]
